version: "3"
services: 
  traefik:
    restart: unless-stopped
    image: "traefik:2.4"
    container_name: "proxy"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik.toml:/traefik.toml:ro"
      - "./conf/traefik_dynamic.toml:/traefik_dynamic.toml:ro"
      - "./cert/acme.json:/acme.json:rw"
networks:
  traefik:
    external: true    
